Add the 'delete dataset' functionality
label-sleuth/label-sleuth pull request #416
Opened 2023-03-09 15:44 UTC by martinscooper

I've started working on [this issue](https://github.com/label-sleuth/label-sleuth/issues/409). First, to improve this first version:
- Improve the wording.
- Make the text that explain that some workspaces may be deleted too to call more the attention of the user. - Maybe we can add a subsequent modal after the first one in case workspaces are going to be deleted.
- Backend changes:
  - add two endpoints: /datasets/<dataset_name>/used_by (GET) , which returns a list of the workspaces that use a particular dataset and /datasets/<dataset_name> (DELETE)
  - add two method to the OrchestratorApi : get_workspaces_by_dataset_name()  and delete_dataset() , delete_dataset calls get_workspaces_by_dataset_name()  to delete workspaces if those are using the dataset that is going to be deleted and then delete them. Finally it calls a new data_access  method to delete the dataset.
  - add delete_dataset  to data_access (file based) . It removes the folder returned by self._get_dataset_base_dir(dataset_name) which now is data_access_dups/<dataset_name> .
  - I know that locks are used when working with workspaces, should we implement a similar mechanism when working with datasets?

2023-03-12 18:31 UTC, alonh approved these changes

2023-03-13 09:48 UTC, arielge requested changes

2023-03-13 09:48 UTC, arielge commented on label_sleuth/app.py
> +    This call permanently deletes all data associated with the given workspace, including all the categories, user
the docstring should be updated

2023-03-13 09:48 UTC, arielge commented on label_sleuth/data_access/file_based/file_based_data_access.py
> +    def delete_dataset(self, dataset_name: str):
A `delete_dataset` method  already exists (line 449/452)

2023-03-13 13:11 UTC, arielge approved these changes

2023-03-13 14:34 UTC, merged