Rename set_element endpoint parameters and refactor
label-sleuth/label-sleuth pull request #618
Opened 2023-11-14 18:27 UTC by martinscooper

solves https://github.com/label-sleuth/label-sleuth/issues/609.

2023-11-15 17:02 UTC, arielge requested changes

2023-11-15 20:22 UTC, martinscooper commented on label_sleuth/orchestrator/orchestrator_api.py
> +                   apply_to_duplicate_texts=True, update_label_counter=True, is_multiclass=False):
I agree, I discarded this change

2023-11-15 20:22 UTC, martinscooper commented on label_sleuth/app.py
> +    if category_id != None:
I agree

2023-11-16 08:36 UTC, arielge approved these changes

2023-11-16 08:36 UTC, merged